### ISSUE TITLE
Generation of files in `coverage_data`

### ISSUE THREAD

**Issue by lvclark** [felixgrunberger/Native_RNAseq_Microbes#1]
I am trying to run `tu_subcluster_annotation.R`, which requires files in `data/coverage_data`.  However, I can't find any scripts or instructions in the rest of the repository explaining how those files should be created.

Thanks in advance!

**Comment by felixgrunberger** [comment]
Sorry that this information is missing. 
Coverage files were generated in a strand-specific way (after filtering the BAM according to the their flags) with `samtools depth -a -d 0` and include the read depth at each position in the genome. 
You can also have a look at https://github.com/felixgrunberger/microbepore/blob/master/Rscripts/operon_analysis.R, which is an updated version of the transcriptional unit analysis.

**Comment by lvclark** [comment]
Great, thank you!

**Comment by lvclark** [comment]
To get forward and reverse coverage I ended up doing

```
samtools view -F 0x10 -h -b results/minimap/${Sample_ID}_sorted.bam | \
  samtools depth -a -d 0 -o Native_RNAseq_Microbes/coverage_data/${Sample_ID}_plus_depth.txt -

samtools view -f 0x10 -h -b results/minimap/${Sample_ID}_sorted.bam | \
  samtools depth -a -d 0 -o Native_RNAseq_Microbes/coverage_data/${Sample_ID}_minus_depth.txt -
```
